In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("/content/petrol_consumption.csv")

In [3]:
dataset

Petrol_tax  ...  Petrol_Consumption
0         9.00  ...                 541
1         9.00  ...                 524
2         9.00  ...                 561
3         7.50  ...                 414
4         8.00  ...                 410
5        10.00  ...                 457
6         8.00  ...                 344
7         8.00  ...                 467
8         8.00  ...                 464
9         7.00  ...                 498
10        8.00  ...                 580
11        7.50  ...                 471
12        7.00  ...                 525
13        7.00  ...                 508
14        7.00  ...                 566
15        7.00  ...                 635
16        7.00  ...                 603
17        7.00  ...                 714
18        7.00  ...                 865
19        8.50  ...                 640
20        7.00  ...                 649
21        8.00  ...                 540
22        9.00  ...                 464
23        9.00  ...                 547
24        8.50  ...                 460
25        9.00  ...                 566
26        8.00  ...                 577
27        7.50  ...                 631
28        8.00  ...                 574
29        9.00  ...                 534
30        7.00  ...                 571
31        7.00  ...                 554
32        8.00  ...                 577
33        7.50  ...                 628
34        8.00  ...                 487
35        6.58  ...                 644
36        5.00  ...                 640
37        7.00  ...                 704
38        8.50  ...                 648
39        7.00  ...                 968
40        7.00  ...                 587
41        7.00  ...                 699
42        7.00  ...                 632
43        7.00  ...                 591
44        6.00  ...                 782
45        9.00  ...                 510
46        7.00  ...                 610
47        7.00  ...                 524

[48 rows x 5 columns]

In [4]:
dataset.isnull().any()

Petrol_tax                      False
Average_income                  False
Paved_Highways                  False
Population_Driver_licence(%)    False
Petrol_Consumption              False
dtype: bool

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Petrol_tax                    48 non-null     float64
 1   Average_income                48 non-null     int64  
 2   Paved_Highways                48 non-null     int64  
 3   Population_Driver_licence(%)  48 non-null     float64
 4   Petrol_Consumption            48 non-null     int64  
dtypes: float64(2), int64(3)
memory usage: 2.0 KB


In [6]:
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

In [7]:
x

array([[9.0000e+00, 3.5710e+03, 1.9760e+03, 5.2500e-01],
       [9.0000e+00, 4.0920e+03, 1.2500e+03, 5.7200e-01],
       [9.0000e+00, 3.8650e+03, 1.5860e+03, 5.8000e-01],
       [7.5000e+00, 4.8700e+03, 2.3510e+03, 5.2900e-01],
       [8.0000e+00, 4.3990e+03, 4.3100e+02, 5.4400e-01],
       [1.0000e+01, 5.3420e+03, 1.3330e+03, 5.7100e-01],
       [8.0000e+00, 5.3190e+03, 1.1868e+04, 4.5100e-01],
       [8.0000e+00, 5.1260e+03, 2.1380e+03, 5.5300e-01],
       [8.0000e+00, 4.4470e+03, 8.5770e+03, 5.2900e-01],
       [7.0000e+00, 4.5120e+03, 8.5070e+03, 5.5200e-01],
       [8.0000e+00, 4.3910e+03, 5.9390e+03, 5.3000e-01],
       [7.5000e+00, 5.1260e+03, 1.4186e+04, 5.2500e-01],
       [7.0000e+00, 4.8170e+03, 6.9300e+03, 5.7400e-01],
       [7.0000e+00, 4.2070e+03, 6.5800e+03, 5.4500e-01],
       [7.0000e+00, 4.3320e+03, 8.1590e+03, 6.0800e-01],
       [7.0000e+00, 4.3180e+03, 1.0340e+04, 5.8600e-01],
       [7.0000e+00, 4.2060e+03, 8.5080e+03, 5.7200e-01],
       [7.0000e+00, 3.7180e+03,

In [8]:
y

array([541, 524, 561, 414, 410, 457, 344, 467, 464, 498, 580, 471, 525,
       508, 566, 635, 603, 714, 865, 640, 649, 540, 464, 547, 460, 566,
       577, 631, 574, 534, 571, 554, 577, 628, 487, 644, 640, 704, 648,
       968, 587, 699, 632, 591, 782, 510, 610, 524])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1000)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
pc = Sequential()

In [13]:
pc.add(Dense(4,kernel_initializer = "random_uniform",activation = "relu"))

In [14]:
pc.add(Dense(8,kernel_initializer = "random_uniform",activation = "relu"))

In [15]:
pc.add(Dense(1,kernel_initializer = "random_uniform",activation = "relu"))

In [16]:
pc.compile("adam","mean_squared_error",metrics = ["MSE"])

In [17]:
pc.fit(x_train,y_train,batch_size = 32,epochs = 10)

Epoch 1/10
2/2 [==============================] - 0s 5ms/step - loss: 361969.5312 - MSE: 361969.5312
Epoch 2/10
2/2 [==============================] - 0s 6ms/step - loss: 365679.9271 - MSE: 365679.9271
Epoch 3/10
2/2 [==============================] - 0s 8ms/step - loss: 359815.3021 - MSE: 359815.3021
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 363623.8438 - MSE: 363623.8438
Epoch 5/10
2/2 [==============================] - 0s 4ms/step - loss: 364364.7083 - MSE: 364364.7083
Epoch 6/10
2/2 [==============================] - 0s 3ms/step - loss: 360212.9792 - MSE: 360212.9792
Epoch 7/10
2/2 [==============================] - 0s 4ms/step - loss: 369835.5417 - MSE: 369835.5417
Epoch 8/10
2/2 [==============================] - 0s 5ms/step - loss: 357497.3021 - MSE: 357497.3021
Epoch 9/10
2/2 [==============================] - 0s 6ms/step - loss: 362545.8229 - MSE: 362545.8229
Epoch 10/10
2/2 [==============================] - 0s 5ms/step - loss: 361085.9896 - MSE: 3

In [18]:
ypred = pc.predict(x_test)
ypred

array([[0.02415353],
       [0.02417855],
       [0.02411679],
       [0.02503075],
       [0.02479839],
       [0.02407591],
       [0.02414286],
       [0.02470039],
       [0.02522064],
       [0.02460815]], dtype=float32)

In [19]:
y_test

array([498, 524, 464, 628, 554, 344, 414, 587, 561, 635])

In [25]:
pc.predict(sc.transform([[9.00,	3571	,1976	,0.525	]]))

array([[0.02501182]], dtype=float32)

In [26]:
pc.predict_classes(sc.transform([[9.00	,3571,	1976	,0.525	]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)

In [27]:
pc.predict(sc.transform([[7.00,3897,	6385,	0.586	]]))

array([[0.02474309]], dtype=float32)

In [28]:
pc.predict_classes(sc.transform([[7.00,3897,	6385,	0.586	]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)