In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("/content/diabetes.csv")

In [3]:
dataset

Pregnancies  Glucose  ...  Age  Diabetes
0              6      148  ...   50       pos
1              8      183  ...   32       pos
2              0      137  ...   33       pos
3              3       78  ...   26       pos
4              2      197  ...   53       pos
..           ...      ...  ...  ...       ...
544           10      101  ...   63       neg
545            2      122  ...   27       neg
546            5      121  ...   30       neg
547            1      126  ...   47       pos
548            1       93  ...   23       neg

[549 rows x 9 columns]

In [4]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Diabetes                    False
dtype: bool

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549 entries, 0 to 548
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               549 non-null    int64  
 1   Glucose                   549 non-null    int64  
 2   BloodPressure             549 non-null    int64  
 3   SkinThickness             549 non-null    int64  
 4   Insulin                   549 non-null    int64  
 5   BMI                       549 non-null    float64
 6   DiabetesPedigreeFunction  549 non-null    float64
 7   Age                       549 non-null    int64  
 8   Diabetes                  549 non-null    object 
dtypes: float64(2), int64(6), object(1)
memory usage: 38.7+ KB


In [6]:
dataset["Diabetes"].unique()

array(['pos', 'neg'], dtype=object)

In [7]:
x= dataset.iloc[:,0:8].values
y= dataset.iloc[:,8:9].values

In [8]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [9]:
y

array([['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       [

In [10]:
y.ndim

2

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one = OneHotEncoder()
z = one.fit_transform(y[:,0:1]).toarray()
y = np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [12]:
z

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [13]:
y

array([[0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       ...,
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0]], dtype=object)

In [14]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
x_train = np.asarray(x_train).astype('float32')
x_test = np.asarray(x_test).astype('float32')
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
abc = Sequential()

In [20]:
abc.add(Dense(8,kernel_initializer ="random_uniform",activation = "relu"))

In [21]:
abc.add(Dense(16,kernel_initializer ="random_uniform",activation = "relu"))

In [22]:
abc.add(Dense(2,kernel_initializer = "random_uniform",activation = "sigmoid"))

In [23]:
abc.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [24]:
abc.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
14/14 [==============================] - 1s 1ms/step - loss: 0.6931 - accuracy: 0.5022
Epoch 2/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6925 - accuracy: 0.5367
Epoch 3/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6907 - accuracy: 0.6024
Epoch 4/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6877 - accuracy: 0.7282
Epoch 5/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6795 - accuracy: 0.7586
Epoch 6/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6657 - accuracy: 0.7813
Epoch 7/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6514 - accuracy: 0.7451
Epoch 8/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6209 - accuracy: 0.7709
Epoch 9/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5999 - accuracy: 0.7878
Epoch 10/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.5781 - accuracy: 0.7881

In [25]:
x_train.shape

(439, 8)

In [26]:
y_train.shape

(439, 2)

In [27]:
ypred = abc.predict(x_test)

In [28]:
ypred

array([[4.9896908e-01, 4.9810305e-01],
       [3.0293763e-03, 9.9699605e-01],
       [9.7779179e-01, 2.2108406e-02],
       [3.3807755e-04, 9.9966145e-01],
       [9.8198265e-01, 1.8114269e-02],
       [2.3324877e-02, 9.7652799e-01],
       [9.9241161e-01, 7.6057613e-03],
       [1.2445706e-01, 8.7473756e-01],
       [3.5496026e-01, 6.4352697e-01],
       [1.2371577e-05, 9.9998784e-01],
       [9.9208736e-01, 7.8965127e-03],
       [1.3315380e-03, 9.9866056e-01],
       [1.0726273e-02, 9.8934084e-01],
       [3.3005831e-01, 6.6930175e-01],
       [8.7555653e-01, 1.2449974e-01],
       [5.5975854e-02, 9.4422472e-01],
       [9.2980826e-01, 7.0959598e-02],
       [7.4808639e-01, 2.5273758e-01],
       [5.7935154e-01, 4.2019570e-01],
       [1.8302318e-01, 8.1855667e-01],
       [9.8216063e-01, 1.7695874e-02],
       [7.0572549e-01, 2.9585344e-01],
       [6.5107298e-01, 3.4724796e-01],
       [4.7727734e-02, 9.5346665e-01],
       [9.9939954e-01, 6.0111284e-04],
       [9.8840892e-01, 1.

In [29]:
ypred[0]

array([0.49896908, 0.49810305], dtype=float32)

In [30]:
y_test[0]

array([0., 1.], dtype=float32)

In [31]:
abc.predict(sc.transform([[6,148,72,35,0,33.6,0.627,50]])) # for this positive 

array([[0.30454695, 0.6950993 ]], dtype=float32)

In [32]:
abc.predict_classes(sc.transform([[6,148,72,35,0,33.6,0.627,50]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1])

In [33]:
abc.predict(sc.transform([[1,93,70,31,0,30.4,0.315,23]]))  # fo this negative

array([[0.8557339 , 0.14444157]], dtype=float32)

In [34]:
abc.predict_classes(sc.transform([[1,93,70,31,0,30.4,0.315,23]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([0])