In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("/content/diabetes.csv")

In [3]:
dataset

Pregnancies  Glucose  ...  Age  Diabetes
0              6      148  ...   50       pos
1              8      183  ...   32       pos
2              0      137  ...   33       pos
3              3       78  ...   26       pos
4              2      197  ...   53       pos
..           ...      ...  ...  ...       ...
544           10      101  ...   63       neg
545            2      122  ...   27       neg
546            5      121  ...   30       neg
547            1      126  ...   47       pos
548            1       93  ...   23       neg

[549 rows x 9 columns]

In [4]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Diabetes                    False
dtype: bool

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549 entries, 0 to 548
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               549 non-null    int64  
 1   Glucose                   549 non-null    int64  
 2   BloodPressure             549 non-null    int64  
 3   SkinThickness             549 non-null    int64  
 4   Insulin                   549 non-null    int64  
 5   BMI                       549 non-null    float64
 6   DiabetesPedigreeFunction  549 non-null    float64
 7   Age                       549 non-null    int64  
 8   Diabetes                  549 non-null    object 
dtypes: float64(2), int64(6), object(1)
memory usage: 38.7+ KB


In [6]:
dataset["Diabetes"].unique()

array(['pos', 'neg'], dtype=object)

In [7]:
x= dataset.iloc[:,0:8].values
y= dataset.iloc[:,8:9].values

In [8]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [9]:
y

array([['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       [

In [10]:
y.ndim

2

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one = OneHotEncoder()
z = one.fit_transform(y[:,0:1]).toarray()
y = np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [12]:
z

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [13]:
y

array([[0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       ...,
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0]], dtype=object)

In [14]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
x_train = np.asarray(x_train).astype('float32')
x_test = np.asarray(x_test).astype('float32')
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
abc = Sequential()

In [20]:
abc.add(Dense(8,kernel_initializer ="random_uniform",activation = "relu"))

In [21]:
abc.add(Dense(16,kernel_initializer ="random_uniform",activation = "relu"))

In [22]:
abc.add(Dense(2,kernel_initializer = "random_uniform",activation = "softmax"))

In [23]:
abc.compile("adam","categorical_crossentropy",metrics = ["accuracy"])

In [27]:
abc.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.2415 - accuracy: 0.9043
Epoch 2/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.2425 - accuracy: 0.9066
Epoch 3/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.2424 - accuracy: 0.9089
Epoch 4/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.2451 - accuracy: 0.9089
Epoch 5/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.2432 - accuracy: 0.9066
Epoch 6/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.2437 - accuracy: 0.9043
Epoch 7/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.2444 - accuracy: 0.9021
Epoch 8/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.2438 - accuracy: 0.9112
Epoch 9/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.2432 - accuracy: 0.9043
Epoch 10/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.2426 - accuracy: 0.9043

In [28]:
x_train.shape

(439, 8)

In [29]:
y_train.shape

(439, 2)

In [30]:
ypred = abc.predict(x_test)

In [31]:
ypred

array([[5.45276748e-03, 9.94547248e-01],
       [7.96183713e-07, 9.99999166e-01],
       [5.92093647e-01, 4.07906353e-01],
       [2.51493066e-06, 9.99997497e-01],
       [9.80624616e-01, 1.93754137e-02],
       [8.50334800e-06, 9.99991536e-01],
       [9.71750379e-01, 2.82496400e-02],
       [1.57173946e-02, 9.84282672e-01],
       [4.03565079e-01, 5.96434951e-01],
       [8.70245648e-14, 1.00000000e+00],
       [9.96379435e-01, 3.62054817e-03],
       [6.71688554e-08, 9.99999881e-01],
       [2.58410107e-02, 9.74159002e-01],
       [5.78133799e-02, 9.42186654e-01],
       [9.45680201e-01, 5.43197766e-02],
       [1.70797538e-02, 9.82920229e-01],
       [5.99203169e-01, 4.00796890e-01],
       [3.12138587e-01, 6.87861383e-01],
       [9.21866298e-01, 7.81337023e-02],
       [8.73146128e-05, 9.99912620e-01],
       [9.85910654e-01, 1.40893441e-02],
       [9.59737420e-01, 4.02625538e-02],
       [5.18268794e-02, 9.48173106e-01],
       [7.89879266e-07, 9.99999166e-01],
       [9.635986

In [32]:
ypred[0]

array([0.00545277, 0.99454725], dtype=float32)

In [33]:
y_test[0]

array([0., 1.], dtype=float32)

In [34]:
abc.predict(sc.transform([[6,148,72,35,0,33.6,0.627,50]])) # for this positive 

array([[0.1289939, 0.8710061]], dtype=float32)

In [35]:
abc.predict_classes(sc.transform([[6,148,72,35,0,33.6,0.627,50]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1])

In [36]:
abc.predict(sc.transform([[1,93,70,31,0,30.4,0.315,23]]))  # fo this negative

array([[0.9790146 , 0.02098541]], dtype=float32)

In [37]:
abc.predict_classes(sc.transform([[1,93,70,31,0,30.4,0.315,23]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([0])