In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("/content/Loanstatus.csv")

In [3]:
dataset.head()

Loan_ID Gender Married  ... Credit_History Property_Area Loan_Status
0  LP001002   Male      No  ...            1.0         Urban           Y
1  LP001003   Male     Yes  ...            1.0         Rural           N
2  LP001005   Male     Yes  ...            1.0         Urban           Y
3  LP001006   Male     Yes  ...            1.0         Urban           Y
4  LP001008   Male      No  ...            1.0         Urban           Y

[5 rows x 13 columns]

In [4]:
dataset.isnull().any()

Loan_ID              False
Gender                True
Married               True
Dependents            True
Education            False
Self_Employed         True
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount            True
Loan_Amount_Term      True
Credit_History        True
Property_Area        False
Loan_Status          False
dtype: bool

In [5]:
dataset.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [7]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)
dataset["Married"].fillna(dataset["Married"].mode()[0],inplace=True)
dataset["Dependents"].fillna(dataset["Dependents"].mode()[0],inplace=True)
dataset["Self_Employed"].fillna(dataset["Self_Employed"].mode()[0],inplace=True)
dataset["LoanAmount"].fillna(dataset["LoanAmount"].mean(),inplace=True)
dataset["Loan_Amount_Term"].fillna(dataset["Loan_Amount_Term"].mean(),inplace=True)
dataset["Credit_History"].fillna(dataset["Credit_History"].mean(),inplace=True)

In [8]:
dataset.isnull().any()

Loan_ID              False
Gender               False
Married              False
Dependents           False
Education            False
Self_Employed        False
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount           False
Loan_Amount_Term     False
Credit_History       False
Property_Area        False
Loan_Status          False
dtype: bool

In [9]:
dataset["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [10]:
dataset["Married"].unique()

array(['No', 'Yes'], dtype=object)

In [11]:
dataset["Education"].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [12]:
dataset["Self_Employed"].unique()

array(['No', 'Yes'], dtype=object)

In [13]:
dataset["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [14]:
dataset["Loan_Status"].unique()

array(['Y', 'N'], dtype=object)

In [15]:
dataset["Dependents"].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [16]:
dataset = dataset.replace(to_replace = "3+",value = 3)

In [17]:
dataset["Dependents"].unique()

array(['0', '1', '2', 3], dtype=object)

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    object 
 2   Married            614 non-null    object 
 3   Dependents         614 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      614 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [19]:
dataset["Dependents"] = dataset["Dependents"].astype(int)

In [20]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    object 
 2   Married            614 non-null    object 
 3   Dependents         614 non-null    int64  
 4   Education          614 non-null    object 
 5   Self_Employed      614 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(2), object(7)
memory usage: 62.5+ KB


In [21]:
x = dataset.iloc[:,1:12].values
y = dataset.iloc[:,12:13].values

In [22]:
x

array([['Male', 'No', 0, ..., 360.0, 1.0, 'Urban'],
       ['Male', 'Yes', 1, ..., 360.0, 1.0, 'Rural'],
       ['Male', 'Yes', 0, ..., 360.0, 1.0, 'Urban'],
       ...,
       ['Male', 'Yes', 1, ..., 360.0, 1.0, 'Urban'],
       ['Male', 'Yes', 2, ..., 360.0, 1.0, 'Urban'],
       ['Female', 'No', 0, ..., 360.0, 0.0, 'Semiurban']], dtype=object)

In [23]:
y

array([['Y'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['Y'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['N'],
       ['Y'],
       ['N'],
       ['Y'],
       ['N'],
       ['N'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['Y'],
       ['N'],
       ['N'],
       ['N'],
       ['Y'],
       ['N'],
       ['Y'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['N'],
       ['N'],
       ['Y'],
       ['Y'],
       ['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['N'],
       ['N'],
       ['N'],
       ['N'],
       ['Y'],
       ['Y'],
       ['N'],
       ['Y'],
      

In [24]:
x.shape

(614, 11)

In [25]:
y.shape

(614, 1)

In [26]:
x[1,:]

array(['Male', 'Yes', 1, 'Graduate', 'No', 4583, 1508.0, 128.0, 360.0,
       1.0, 'Rural'], dtype=object)

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [28]:
ct = ColumnTransformer([("oh",OneHotEncoder(),[0,1,3,4,10])],remainder ="passthrough")
x=ct.fit_transform(x)

In [29]:
one = OneHotEncoder()
z = one.fit_transform(y[:,0:1]).toarray()
y = np.delete(y,0,axis=1)
y =np.concatenate((z,y),axis=1)

In [30]:
x.shape

(614, 17)

In [59]:
x[0:2]

array([[0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0, 5849,
        0.0, 146.41216216216216, 360.0, 1.0],
       [0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1, 4583,
        1508.0, 128.0, 360.0, 1.0]], dtype=object)

In [31]:
y

array([[0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       ...,
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0]], dtype=object)

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [33]:
x_train = np.asarray(x_train).astype('float32')
x_test = np.asarray(x_test).astype('float32')
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [36]:
ls = Sequential()

In [37]:
ls.add(Dense(11,kernel_initializer="random_uniform",activation="relu"))

In [38]:
ls.add(Dense(22,kernel_initializer="random_uniform",activation="relu"))

In [39]:
ls.add(Dense(2,kernel_initializer="random_uniform",activation="softmax"))

In [40]:
ls.compile("adam","categorical_crossentropy",metrics =["accuracy"])

In [42]:
ls.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 1ms/step - loss: 0.3974 - accuracy: 0.8391
Epoch 2/100
16/16 [==============================] - 0s 1ms/step - loss: 0.3993 - accuracy: 0.8350
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 0.3980 - accuracy: 0.8350
Epoch 4/100
16/16 [==============================] - 0s 1ms/step - loss: 0.3955 - accuracy: 0.8371
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 0.3949 - accuracy: 0.8371
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 0.3927 - accuracy: 0.8371
Epoch 7/100
16/16 [==============================] - 0s 1ms/step - loss: 0.3934 - accuracy: 0.8391
Epoch 8/100
16/16 [==============================] - 0s 1ms/step - loss: 0.3927 - accuracy: 0.8391
Epoch 9/100
16/16 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.8391
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 0.3918 - accuracy: 0.8391
Epoch 11/

In [43]:
ypred = ls.predict(x_test)

In [44]:
ypred

array([[5.52207053e-01, 4.47792977e-01],
       [6.43895939e-02, 9.35610414e-01],
       [1.97255597e-01, 8.02744389e-01],
       [5.83696783e-01, 4.16303217e-01],
       [3.41801904e-02, 9.65819836e-01],
       [9.99782622e-01, 2.17448629e-04],
       [7.06806779e-02, 9.29319322e-01],
       [1.36554837e-01, 8.63445163e-01],
       [1.49048597e-01, 8.50951374e-01],
       [9.71033037e-01, 2.89669596e-02],
       [6.47962391e-01, 3.52037549e-01],
       [2.95728818e-02, 9.70427155e-01],
       [1.03716977e-01, 8.96283031e-01],
       [3.57237041e-01, 6.42762959e-01],
       [2.75917321e-01, 7.24082708e-01],
       [5.88507950e-02, 9.41149235e-01],
       [2.63040233e-02, 9.73695993e-01],
       [5.99637032e-02, 9.40036356e-01],
       [1.33508042e-01, 8.66492033e-01],
       [1.34200290e-01, 8.65799725e-01],
       [9.84811112e-02, 9.01518881e-01],
       [5.33922687e-02, 9.46607769e-01],
       [3.35229486e-01, 6.64770544e-01],
       [2.97744982e-02, 9.70225453e-01],
       [2.938683

In [45]:
y_test

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [46]:
ypred[0]

array([0.55220705, 0.44779298], dtype=float32)

In [47]:
y_test[0]

array([1., 0.], dtype=float32)

In [57]:
ls.predict(sc.transform([[0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0, 5849, 0.0, 146.41216216216216, 360.0, 1.0]]))

array([[0.33522958, 0.6647704 ]], dtype=float32)

In [56]:
ls.predict_classes(sc.transform([[0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0, 5849, 0.0, 146.41216216216216, 360.0, 1.0]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1])