In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/content/bank.csv")

In [3]:
data.head()

age         job  marital  education  ... pdays  previous poutcome deposit
0   59      admin.  married  secondary  ...    -1         0  unknown     yes
1   56      admin.  married  secondary  ...    -1         0  unknown     yes
2   41  technician  married  secondary  ...    -1         0  unknown     yes
3   55    services  married  secondary  ...    -1         0  unknown     yes
4   54      admin.  married   tertiary  ...    -1         0  unknown     yes

[5 rows x 17 columns]

In [4]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
data = data.drop(['marital','education','default'],axis=1)

In [6]:
data.head()

age         job  balance housing  ... pdays previous  poutcome deposit
0   59      admin.     2343     yes  ...    -1        0   unknown     yes
1   56      admin.       45      no  ...    -1        0   unknown     yes
2   41  technician     1270     yes  ...    -1        0   unknown     yes
3   55    services     2476     yes  ...    -1        0   unknown     yes
4   54      admin.      184      no  ...    -1        0   unknown     yes

[5 rows x 14 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   age       11162 non-null  int64 
 1   job       11162 non-null  object
 2   balance   11162 non-null  int64 
 3   housing   11162 non-null  object
 4   loan      11162 non-null  object
 5   contact   11162 non-null  object
 6   day       11162 non-null  int64 
 7   month     11162 non-null  object
 8   duration  11162 non-null  int64 
 9   campaign  11162 non-null  int64 
 10  pdays     11162 non-null  int64 
 11  previous  11162 non-null  int64 
 12  poutcome  11162 non-null  object
 13  deposit   11162 non-null  object
dtypes: int64(7), object(7)
memory usage: 1.2+ MB


In [8]:
data.job.unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [10]:
data.housing.unique()

array(['yes', 'no'], dtype=object)

In [11]:
data.loan.unique()

array(['no', 'yes'], dtype=object)

In [12]:
data.contact.unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [13]:
data.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [14]:
data.poutcome.unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["job"] = le.fit_transform(data["job"])
data["housing"] = le.fit_transform(data["housing"])
data["loan"] = le.fit_transform(data["loan"])
data["contact"] = le.fit_transform(data["contact"])
data["month"] = le.fit_transform(data["month"])
data["poutcome"] = le.fit_transform(data["poutcome"])
data["deposit"] = le.fit_transform(data["deposit"])

In [45]:
data.tail()

age  job  balance  housing  ...  pdays  previous  poutcome  deposit
11157   33    1        1        1  ...     -1         0         3        0
11158   39    7      733        0  ...     -1         0         3        0
11159   32    9       29        0  ...     -1         0         3        0
11160   43    9        0        0  ...    172         5         0        0
11161   34    9        0        0  ...     -1         0         3        0

[5 rows x 14 columns]

In [17]:
x = data.iloc[:,0:13].values
y = data.iloc[:,13].values

In [18]:
x.shape

(11162, 13)

In [19]:
y.shape

(11162,)

In [20]:
x

array([[  59,    0, 2343, ...,   -1,    0,    3],
       [  56,    0,   45, ...,   -1,    0,    3],
       [  41,    9, 1270, ...,   -1,    0,    3],
       ...,
       [  32,    9,   29, ...,   -1,    0,    3],
       [  43,    9,    0, ...,  172,    5,    0],
       [  34,    9,    0, ...,   -1,    0,    3]])

In [21]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [25]:
b = Sequential()

In [26]:
b.add(Dense(13,kernel_initializer="random_uniform",activation="relu"))

In [27]:
b.add(Dense(26,kernel_initializer="random_uniform",activation="relu"))

In [28]:
b.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [29]:
b.compile("adam","binary_crossentropy",metrics =["accuracy"])

In [30]:
b.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
280/280 [==============================] - 1s 2ms/step - loss: 0.6317 - accuracy: 0.6825
Epoch 2/100
280/280 [==============================] - 0s 2ms/step - loss: 0.4571 - accuracy: 0.7969
Epoch 3/100
280/280 [==============================] - 0s 1ms/step - loss: 0.4421 - accuracy: 0.8043
Epoch 4/100
280/280 [==============================] - 0s 2ms/step - loss: 0.4318 - accuracy: 0.8097
Epoch 5/100
280/280 [==============================] - 0s 2ms/step - loss: 0.4361 - accuracy: 0.8069
Epoch 6/100
280/280 [==============================] - 0s 1ms/step - loss: 0.4409 - accuracy: 0.8095
Epoch 7/100
280/280 [==============================] - 0s 1ms/step - loss: 0.4425 - accuracy: 0.8003
Epoch 8/100
280/280 [==============================] - 0s 1ms/step - loss: 0.4362 - accuracy: 0.8079
Epoch 9/100
280/280 [==============================] - 0s 1ms/step - loss: 0.4168 - accuracy: 0.8213
Epoch 10/100
280/280 [==============================] - 0s 1ms/step - loss: 0.4331 - accura

In [31]:
ypred = b.predict(x_test)

In [32]:
ypred

array([[0.85008955],
       [0.7085277 ],
       [0.27104628],
       ...,
       [0.93710726],
       [0.7917696 ],
       [0.54664785]], dtype=float32)

In [33]:
y_test

array([0, 1, 0, ..., 1, 1, 1])

In [34]:
ypred[0]

array([0.85008955], dtype=float32)

In [35]:
y_test[0]

0

In [40]:
x[11161,:]

array([ 34,   9,   0,   0,   0,   0,   9,   5, 628,   1,  -1,   0,   3])

In [37]:
b.predict(sc.transform([[59,0,2343,1,0,2,5,8,1042,1,-1,0,3]]))

array([[0.81633306]], dtype=float32)

In [38]:
b.predict_classes(sc.transform([[59,0,2343,1,0,2,5,8,1042,1,-1,0,3]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]], dtype=int32)

In [49]:
b.predict(sc.transform([[39	,7	,733	,0	,0	,2	,16	,6	,83,	4	,-1	,0	,3]]))

array([[0.00118667]], dtype=float32)

In [50]:
b.predict_classes(sc.transform([[39	,7	,733	,0	,0	,2	,16	,6	,83,	4	,-1	,0	,3]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)